const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const codigo=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1],nos={};
const no=id=>nos[id]||=( {id,value:'',attrs:{},setAttribute(k,v){this.attrs[k]=v;}} );
const st={sec:'geral',modoEmp:'mosaico',modoBdr:'tabela',q:'',cats:new Set(),tags:new Set(),tagMode:'ou',sort:'vm',area:'val',qb:'',bdrPais:new Set(),bdrSetor:new Set(),bdrIndustria:new Set(),bdrLiq:'todas',bdrFreq:'todas',bdrHist:'todos',bdrSort:'g20',bdrDir:'desc',recorte:null,soFav:false,matX:'g20',matY:'forca',ativo:null,modoEtf:'tabela',qe:'',etfCategoria:new Set(),etfCobertura:'todos',etfClasse:new Set(),etfFoco:new Set(),etfGeo:new Set(),etfCaracteristica:new Set(),etfSort:'nome',etfDir:'asc'};
const E=[{tagsL:['Petróleo, gás','Exportação']},{tagsL:['Exportação']}],CORES={'Petroleo, Gas e Petroquimica':'#000','Saude':'#fff'},COLS=[{k:'g20'},{k:'r63'},{k:'ticker'}],BDR=[{pais:'United States',setor:'Technology',industria:'Oil, Gas & Consumable Fuels'},{pais:'Canada',setor:'Energy',industria:'Banks'}];
const COLS_ETF=[{k:'ticker'},{k:'nome'},{k:'categoria'},{k:'preco'}],CATEGORIAS_ETF=new Set(['ETF','ETF-RF','ETF-CRIPTO','ETF-INT-RF','ETF-FII','ETF-MOEDA']),ETF_DETALHE=new Map([
  ['BOVA11',{classificacao:{classesAtivo:['acoes'],focoPrincipal:'mercado-amplo',geografia:{escopo:'brasil'},setores:[],temas:[],fatores:[]}}],
  ['DIVO11',{classificacao:{classesAtivo:['acoes'],focoPrincipal:'renda',geografia:{escopo:'brasil'},setores:[],temas:[],fatores:['dividendos']}}]
]),caracEtf=d=>d?[...d.classificacao.setores,...d.classificacao.temas,...d.classificacao.fatores]:[];
let url='';const ctx=vm.createContext({console,st,E,CORES,COLS,BDR,COLS_ETF,CATEGORIAS_ETF,ETF_DETALHE,caracEtf,URLSearchParams,innerWidth:1200,location:{search:''},history:{replaceState:(a,b,u)=>url=u},SECOES:{geral:{},empresas:{},bdrs:{},etfs:{},carteira:{},radar:{},metodologia:{}},LIQ:{todas:{},'10k':{}},FREQ:{todas:{},alta:{}},HIST:{todos:{},com:{}},RECORTES:{forca:{}},eixosMatriz:(x,y)=>({x:['g20','r63'].includes(x)?x:'g20',y:['forca','r63'].includes(y)?y:'forca'}),$:no});
vm.runInContext(codigo.slice(codigo.indexOf('function sincronizaURL('),codigo.indexOf('const SECOES =')),ctx);
Object.assign(st,{sec:'empresas',modoEmp:'tabela',q:'PETR4',tagMode:'e',sort:'nome',area:'igual',ativo:'PETR'});st.cats.add('Petroleo, Gas e Petroquimica');st.cats.add('Saude');st.tags.add('Petróleo, gás');st.tags.add('Exportação');ctx.sincronizaURL();
let p=new URLSearchParams(url);assert.deepEqual(p.getAll('categoria'),['Petroleo, Gas e Petroquimica','Saude']);assert.deepEqual(p.getAll('tag'),['Exportação','Petróleo, gás']);for(const [k,v] of [['modo','tabela'],['tags','e'],['ord','nome'],['area','igual'],['ativo','PETR']])assert.equal(p.get(k),v);
Object.assign(st,{modoEmp:'mosaico',q:'velho',tagMode:'ou',sort:'vm',area:'val',ativo:'velho'});st.cats.clear();st.tags.clear();ctx.location.search=url;ctx.leURL();assert.equal(st.modoEmp,'tabela');assert.equal(st.q,'PETR4');assert.equal(st.tagMode,'e');assert.equal(st.sort,'nome');assert.equal(st.area,'igual');assert.deepEqual([...st.cats].sort(),['Petroleo, Gas e Petroquimica','Saude']);assert.deepEqual([...st.tags].sort(),['Exportação','Petróleo, gás']);
ctx.refleteEstado();assert.equal(no('qEmp').value,'PETR4');assert.equal(no('ordEmp').value,'nome');assert.equal(no('aIgual').attrs['aria-pressed'],'true');assert.equal(no('mE').attrs['aria-pressed'],'true');assert.equal(no('mTabelaE').attrs['aria-pressed'],'true');
ctx.location.search='?sec=empresas';ctx.leURL();assert.equal(st.modoEmp,'mosaico');assert.equal(st.q,'');assert.equal(st.cats.size+st.tags.size,0);assert.equal(st.tagMode,'ou');assert.equal(st.sort,'vm');assert.equal(st.area,'val');assert.equal(st.ativo,null);
ctx.innerWidth=375;ctx.leURL();assert.equal(st.modoEmp,'tabela');ctx.location.search='?sec=empresas&modo=mosaico';ctx.leURL();assert.equal(st.modoEmp,'mosaico');
ctx.location.search='?sec=empresas&modo=errado&tags=errado&ord=constructor&area=errada&categoria=Inexistente&tag=Inexistente&q='+encodeURIComponent('x'.repeat(250));ctx.leURL();assert.equal(st.modoEmp,'tabela');assert.equal(st.tagMode,'ou');assert.equal(st.sort,'vm');assert.equal(st.area,'val');assert.equal(st.cats.size+st.tags.size,0);assert.equal(st.q.length,200);
Object.assign(st,{sec:'bdrs',modoBdr:'matriz',qb:'apple',bdrLiq:'10k',bdrFreq:'alta',bdrHist:'com',bdrSort:'r63',bdrDir:'asc',recorte:'forca',soFav:true,matX:'r63',matY:'r63',ativo:'AAPL34'});st.bdrPais.add('United States');st.bdrPais.add('Canada');st.bdrSetor.add('Technology');st.bdrIndustria.add('Oil, Gas & Consumable Fuels');ctx.sincronizaURL();p=new URLSearchParams(url);assert.deepEqual(p.getAll('pais'),['Canada','United States']);assert.deepEqual(p.getAll('industria'),['Oil, Gas & Consumable Fuels']);
Object.assign(st,{modoBdr:'cards',qb:'velho',bdrLiq:'todas',bdrFreq:'todas',bdrHist:'todos',bdrSort:'ticker',bdrDir:'desc',recorte:null,soFav:false});ctx.location.search=url;ctx.leURL();assert.equal(st.modoBdr,'matriz');assert.equal(st.qb,'apple');assert.equal(st.bdrSort,'r63');assert.equal(st.bdrDir,'asc');assert.equal(st.soFav,true);assert.deepEqual([...st.bdrPais],['Canada','United States']);
ctx.location.search='?sec=bdrs&modo=errado&ord=constructor&dir=errada&liq=errada&freq=errada&hist=errado&recorte=constructor';ctx.leURL();assert.equal(st.modoBdr,'tabela');assert.equal(st.bdrSort,'g20');assert.equal(st.bdrDir,'desc');assert.equal(st.bdrLiq,'todas');assert.equal(st.recorte,null);assert.equal(st.bdrPais.size,0);assert.equal(st.soFav,false);
st.bdrPais.add('United States,Canada');st.bdrPais.add('Falso');st.bdrIndustria.add('Oil, Gas & Consumable Fuels');ctx.normalizaSelecoesBDR();assert.deepEqual([...st.bdrPais],['United States','Canada']);assert.deepEqual([...st.bdrIndustria],['Oil, Gas & Consumable Fuels']);
Object.assign(st,{sec:'etfs',modoEtf:'cards',qe:'bova',etfCobertura:'detalhados',etfSort:'categoria',etfDir:'desc',ativo:'BOVA11'});st.etfCategoria.add('ETF');st.etfCategoria.add('ETF-RF');st.etfClasse.add('acoes');st.etfFoco.add('mercado-amplo');st.etfGeo.add('brasil');st.etfCaracteristica.add('dividendos');ctx.sincronizaURL();p=new URLSearchParams(url);assert.deepEqual(p.getAll('categoria'),['ETF','ETF-RF']);assert.deepEqual(p.getAll('classe'),['acoes']);assert.deepEqual(p.getAll('caracteristica'),['dividendos']);for(const [k,v] of [['modo','cards'],['q','bova'],['cobertura','detalhados'],['ord','categoria'],['dir','desc'],['ativo','BOVA11']])assert.equal(p.get(k),v);
Object.assign(st,{modoEtf:'tabela',qe:'velho',etfCobertura:'todos',etfSort:'nome',etfDir:'asc'});st.etfCategoria.clear();st.etfClasse.clear();st.etfFoco.clear();st.etfGeo.clear();st.etfCaracteristica.clear();ctx.location.search=url;ctx.leURL();assert.equal(st.modoEtf,'cards');assert.equal(st.qe,'bova');assert.equal(st.etfCobertura,'detalhados');assert.equal(st.etfSort,'categoria');assert.equal(st.etfDir,'desc');assert.deepEqual([...st.etfCategoria].sort(),['ETF','ETF-RF']);assert.deepEqual([...st.etfClasse],['acoes']);assert.deepEqual([...st.etfFoco],['mercado-amplo']);assert.deepEqual([...st.etfGeo],['brasil']);assert.deepEqual([...st.etfCaracteristica],['dividendos']);
ctx.refleteEstado();assert.equal(no('qEtf').value,'bova');assert.equal(no('mCardsEtf').attrs['aria-pressed'],'true');assert.equal(no('mTabelaEtf').attrs['aria-pressed'],'false');
ctx.location.search='?sec=etfs&modo=errado&ord=constructor&dir=errada&categoria=Inexistente&cobertura=errada&classe=falsa&foco=renda&geo=brasil&caracteristica=dividendos';ctx.leURL();assert.equal(st.modoEtf,'tabela');assert.equal(st.etfCobertura,'todos');assert.equal(st.etfSort,'nome');assert.equal(st.etfDir,'asc');assert.equal(st.etfCategoria.size,0);ctx.normalizaSelecoesETF();assert.equal(st.etfClasse.size,0);assert.deepEqual([...st.etfFoco],['renda']);assert.deepEqual([...st.etfGeo],['brasil']);assert.deepEqual([...st.etfCaracteristica],['dividendos']);
ctx.location.search='?sec=carteira';ctx.leURL();assert.equal(st.sec,'carteira');ctx.sincronizaURL();assert.equal(new URLSearchParams(url).get('sec'),'carteira');
ctx.location.search='?sec=desconhecida&ativo=AAPL34';ctx.leURL();assert.equal(st.sec,'geral');assert.equal(st.ativo,'AAPL34');
const pop=codigo.match(/addEventListener\('popstate',[^\n]+/)[0];assert.ok(pop.indexOf('URL_ATIVA=false')<pop.indexOf('fecha()'));assert.ok(pop.indexOf('leURL()')<pop.indexOf('refleteEstado()'));
console.log('OK: URL, padrões, parâmetros inválidos, vírgulas, controles, celular, filtros BDR, filtros ETF e retorno do navegador');
